### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by StepanPazderka** [NicoMulet/WeatherSwiftUI#1]
I tried to download this and take a look. Out of curiosity, since I am learning.... but there are some missing files. 

![Missing files](https://user-images.githubusercontent.com/15315282/101548015-7cbec500-39ab-11eb-8482-83d8a2e1d738.png)

**Comment by NicoMulet** [comment]
Thanks for you feedback. I've just resolved the issue on `master`.

**Comment by mtanrw** [comment]
The code Crashes on the ForEach in the CityList view beacause of an index out of range.
